<?php
$T = [
    "es" => [
        "titulo_login" => "Tienda Inazuma",
        "bienvenido" => "Bienvenido",
        "admin" => "Hola capitán",
        "cerrar_sesion" => "Cerrar sesión",
        "añadir_carrito" => "Añadir al Carrito",
        "carrito" => "Carrito",
        "preferencias" => "Preferencias",
        "idioma" => "Idioma",
        "estilo" => "Estilo de la letra",
        "tema" => "Tema",
        "añadir_deseos" => "Añadir a deseos",
        "lista_deseos" => "Lista de deseos",
        "iniciar_sesion" => "Iniciar sesión",
        "usuario_incorrecto" => "Usuario o contraseña incorrectos.",
        "nombre_usuario" => "Nombre de usuario",
        "contraseña" => "Contraseña",
        "espaniol" => "Español",
        "ingles" => "Ingles",
        "claro" => "Claro",
        "oscuro" => "Oscuro",
        "normal" => "Normal",
        "guardar" => "Guardar",
        "volver" =>  "Volver",
        "error_login" => "Fuera de juego"
    ],
    
    "en" => [
        "titulo_login" => "Inazuma Shop",
        "bienvenido" => "Welcome",
        "admin" => "Hello captain",
        "cerrar_sesion" => "Log out",
        "carrito" => "Cart",
        "añadir_carrito" => "Add to Cart",
        "preferencias" => "Preferences",
        "idioma" => "Language",
        "estilo" => "Style of the letter",
        "tema" => "Theme",
        "lista_deseos" => "Wishlist",
        "añadir_deseos" => "Add to Wishlist",
        "iniciar_sesion" => "Log in",
        "usuario_incorrecto" => "Incorrect username or password.",
        "nombre_usuario" => "Username",
        "contraseña" => "Password",
        "error_login" => "Outside",
        "espaniol" => "Spanish",
        "ingles" => "English",
        "claro" => "Clear",
        "oscuro" => "Dark",
        "normal" => "Normal",
        "guardar" => "Keep",
        "volver" =>  "Return",
        "error_login" => "outside"
    ],
];
